name: GCC 13 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Install GCC 13
      uses: aminya/setup-cpp@v1
      with:
        compiler: gcc-13

    - name: Checkout
      uses: actions/checkout@v4

    - name: make
      run: make

    - name: tests
      run: ./tests/run.sh
